# Provision based on https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner

apiVersion: storage.k8s.io/v1 # Versão da API do Kubernetes
kind: StorageClass # Tipo de objeto que estamos criando, no caso um StorageClass
metadata: # Informações sobre o objeto
  name: nfs-subdir-lab # Nome do nosso StorageClass
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: cluster.local/nfs-subdir-external-provisioner # Utilizando o nfs-provision
reclaimPolicy: Retain # Política de reivindicação do PV, ou seja, o PV não será excluído quando o PVC for excluído
volumeBindingMode: Immediate
parameters: # Parâmetros que serão utilizados pelo provisionador
  archiveOnDelete: "false"
  pathPattern: ${.PVC.namespace}-${.PVC.name} # em que pasta os dados de cada PVC serão salvos