# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\";\n\x0cInputNumbers\x12\x14\n\x0c\x66irst_number\x18\x01 \x01(\x02\x12\x15\n\rsecond_number\x18\x02 \x01(\x02\" \n\x0c\x43\x61lcResponse\x12\x10\n\x08response\x18\x01 \x01(\x02\x32\xa5\x01\n\nCalculator\x12(\n\x08Multiply\x12\r.InputNumbers\x1a\r.CalcResponse\x12#\n\x03Sum\x12\r.InputNumbers\x1a\r.CalcResponse\x12#\n\x03\x44iv\x12\r.InputNumbers\x1a\r.CalcResponse\x12#\n\x03Sub\x12\r.InputNumbers\x1a\r.CalcResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INPUTNUMBERS']._serialized_start=20
  _globals['_INPUTNUMBERS']._serialized_end=79
  _globals['_CALCRESPONSE']._serialized_start=81
  _globals['_CALCRESPONSE']._serialized_end=113
  _globals['_CALCULATOR']._serialized_start=116
  _globals['_CALCULATOR']._serialized_end=281
# @@protoc_insertion_point(module_scope)
