apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
      - name: armazenamento-persistente
        mountPath: /usr/share/nginx/
    resources: {}
  volumes:
  - name: armazenamento-persistente
    persistentVolumeClaim:
      claimName: meu-pvc

    
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
